# permissions for end users to view configmaptemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmaptemplate-viewer-role
rules:
- apiGroups:
  - k8s.camtap.io
  resources:
  - configmaptemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.camtap.io
  resources:
  - configmaptemplates/status
  verbs:
  - get
